colors = [
    "nero",
    "blu",
    "marrone",
    "ciano",
    "verde",
    "azzurro",
    "grigio chiaro",
    "grigio",
    "lime",
    "magenta",
    "arancione",
    "rosa",
    "viola",
    "rosso",
    "bianco",
    "giallo",
]

colors_eng = [
    "black",
    "blue",
    "brown",
    "cyan",
    "green",
    "light blue",
    "light gray",
    "gray",
    "lime",
    "magenta",
    "orange",
    "pink",
    "purple",
    "red",
    "white",
    "yellow",
]

fish_types = [
    "pesce creta",
    "pesce striato",
    "pesce scintilla",
    "pesce salterino",
    "pesce raggio di sole",
    "pesce blocco",
    "pesce macchia",
    "betty",
    "kob",
    "pesce pelagico",
    "pesce ficcanaso",
    "pesce scatto",
]

fish_types_eng = [
    "clayfish",
    "stripey",
    "glitter",
    "flopper",
    "sunstreak",
    "blockfish",
    "spotty",
    "betty",
    "kob",
    "brinely",
    "snooper",
    "dasher",
]


fish_name = [
    "anfiprione",
    "pesce chirurgo blu",
    "pesce chirurgo nero",
    "pesce chirurgo giallo",
    "pesce farfalla",
    "pesce farfalla ornato",
    "ciclide",
    "pesce pagliaccio",
    "pesce combattente rosa",
    "pseudocromide",
    "azzannatore rosso",
    "triglia",
    "idolo moresco",
    "pesce pappagallo",
    "pesce angelo regina",
    "ciclide rosso",
    "bavosa rossa",
    "dentice rosso",
    "pesce capitano",
    "pesce pagliaccio pomodoro",
    "pesce balestra",
    "pesce pappagallo a pinna gialla",
]

fish_name_eng = [
    "anemone",
    "blue tang",
    "black tang",
    "yellow tang",
    "butterflyfish",
    "ornate butterflyfish",
    "cichlid",
    "clownfish",
    "cotton candy betta",
    "dottyback",
    "emperor red snapper",
    "goatfish",
    "moorish idol",
    "parrotfish",
    "queen angelfish",
    "red cichlid",
    "red lipped blenny",
    "red snapper",
    "threadfin",
    "tomato clownfish",
    "triggerfish",
    "yellowtail parrotfish",
]
